// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Academic Qualifications documents */
interface AcademicQualificationsDocumentData {
  /**
   * Degrees field in *Academic Qualifications*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: academic_qualifications.degrees[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  degrees: prismicT.GroupField<
    Simplify<AcademicQualificationsDocumentDataDegreesItem>
  >;
}
/**
 * Item in Academic Qualifications → Degrees
 *
 */
export interface AcademicQualificationsDocumentDataDegreesItem {
  /**
   * Establishment Name field in *Academic Qualifications → Degrees*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: academic_qualifications.degrees[].establishment_name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  establishment_name: prismicT.KeyTextField;
  /**
   * Establishment Link field in *Academic Qualifications → Degrees*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: academic_qualifications.degrees[].establishment_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  establishment_link: prismicT.LinkField;
  /**
   * Location field in *Academic Qualifications → Degrees*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: academic_qualifications.degrees[].location
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  location: prismicT.KeyTextField;
  /**
   * Graduation Year field in *Academic Qualifications → Degrees*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: academic_qualifications.degrees[].graduation_year
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  graduation_year: prismicT.NumberField;
  /**
   * Title field in *Academic Qualifications → Degrees*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: academic_qualifications.degrees[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
}
/**
 * Academic Qualifications document from Prismic
 *
 * - **API ID**: `academic_qualifications`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AcademicQualificationsDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<AcademicQualificationsDocumentData>,
    "academic_qualifications",
    Lang
  >;
/** Content for Career Experiences documents */
interface CareerExperiencesDocumentData {
  /**
   * Experiences field in *Career Experiences*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: career_experiences.experiences[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  experiences: prismicT.GroupField<
    Simplify<CareerExperiencesDocumentDataExperiencesItem>
  >;
}
/**
 * Item in Career Experiences → Experiences
 *
 */
export interface CareerExperiencesDocumentDataExperiencesItem {
  /**
   * Company Link field in *Career Experiences → Experiences*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: career_experiences.experiences[].company_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  company_link: prismicT.LinkField;
  /**
   * Company Name field in *Career Experiences → Experiences*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: career_experiences.experiences[].company_name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  company_name: prismicT.KeyTextField;
  /**
   * Location field in *Career Experiences → Experiences*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: career_experiences.experiences[].location
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  location: prismicT.KeyTextField;
  /**
   * Job Title field in *Career Experiences → Experiences*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: career_experiences.experiences[].job_title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  job_title: prismicT.KeyTextField;
  /**
   * Start Date field in *Career Experiences → Experiences*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: career_experiences.experiences[].start_date
   * - **Documentation**: https://prismic.io/docs/core-concepts/date
   *
   */
  start_date: prismicT.DateField;
  /**
   * Present field in *Career Experiences → Experiences*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: career_experiences.experiences[].present
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  present: prismicT.BooleanField;
  /**
   * End Date field in *Career Experiences → Experiences*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: career_experiences.experiences[].end_date
   * - **Documentation**: https://prismic.io/docs/core-concepts/date
   *
   */
  end_date: prismicT.DateField;
  /**
   * Contract Type field in *Career Experiences → Experiences*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: career_experiences.experiences[].contract_type
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  contract_type: prismicT.KeyTextField;
  /**
   * Lede field in *Career Experiences → Experiences*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: career_experiences.experiences[].lede
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  lede: prismicT.RichTextField;
  /**
   * Projects field in *Career Experiences → Experiences*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: career_experiences.experiences[].projects
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  projects: prismicT.RelationField<"projects">;
}
/**
 * Career Experiences document from Prismic
 *
 * - **API ID**: `career_experiences`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CareerExperiencesDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<CareerExperiencesDocumentData>,
    "career_experiences",
    Lang
  >;
/** Content for Home documents */
interface HomeDocumentData {
  /**
   * Title 1 field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title_1: prismicT.KeyTextField;
  /**
   * Paragraph 1 field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.paragraph_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  paragraph_1: prismicT.RichTextField;
  /**
   * Title 2 field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title_2: prismicT.KeyTextField;
  /**
   * Paragraph 2 field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.paragraph_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  paragraph_2: prismicT.RichTextField;
  /**
   * Skills Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.skills_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  skills_section_title: prismicT.KeyTextField;
  /**
   * Tools Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.tools_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  tools_section_title: prismicT.KeyTextField;
  /**
   * Profile Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.profile_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  profile_section_title: prismicT.KeyTextField;
  /**
   * Academic Qualifications Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.academic_qualifications_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  academic_qualifications_section_title: prismicT.KeyTextField;
  /**
   * Languages Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.languages_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  languages_section_title: prismicT.KeyTextField;
  /**
   * Interests Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.interests_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  interests_section_title: prismicT.KeyTextField;
  /**
   * Social Media Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.social_media_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  social_media_section_title: prismicT.KeyTextField;
  /**
   * Career Experiences Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.career_experiences_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  career_experiences_section_title: prismicT.KeyTextField;
  /**
   * Open Source Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.open_source_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  open_source_section_title: prismicT.KeyTextField;
  /**
   * Personal Works Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.personal_works_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  personal_works_section_title: prismicT.KeyTextField;
  /**
   * Get In Touch Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.get_in_touch_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  get_in_touch_section_title: prismicT.KeyTextField;
}
/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;
/** Content for Interests documents */
interface InterestsDocumentData {
  /**
   * Interests field in *Interests*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: interests.interests
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  interests: prismicT.RichTextField;
}
/**
 * Interests document from Prismic
 *
 * - **API ID**: `interests`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InterestsDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<InterestsDocumentData>,
    "interests",
    Lang
  >;
/** Content for Languages documents */
interface LanguagesDocumentData {
  /**
   * Languages field in *Languages*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: languages.languages
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  languages: prismicT.RichTextField;
}
/**
 * Languages document from Prismic
 *
 * - **API ID**: `languages`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LanguagesDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<LanguagesDocumentData>,
    "languages",
    Lang
  >;
/** Content for Open-Source documents */
interface OpenSourceDocumentData {
  /**
   * Projects field in *Open-Source*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: open_source.projects[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  projects: prismicT.GroupField<Simplify<OpenSourceDocumentDataProjectsItem>>;
}
/**
 * Item in Open-Source → Projects
 *
 */
export interface OpenSourceDocumentDataProjectsItem {
  /**
   * Name field in *Open-Source → Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: open_source.projects[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField;
  /**
   * Link field in *Open-Source → Projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: open_source.projects[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismicT.LinkField;
  /**
   * Lede field in *Open-Source → Projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: open_source.projects[].lede
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  lede: prismicT.RichTextField;
  /**
   * Description field in *Open-Source → Projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: open_source.projects[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
}
/**
 * Open-Source document from Prismic
 *
 * - **API ID**: `open_source`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OpenSourceDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<OpenSourceDocumentData>,
    "open_source",
    Lang
  >;
/** Content for Personal Works documents */
interface PersonalWorksDocumentData {
  /**
   * Paragraph field in *Personal Works*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: personal_works.paragraph
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  paragraph: prismicT.RichTextField;
  /**
   * Works field in *Personal Works*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: personal_works.works[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  works: prismicT.GroupField<Simplify<PersonalWorksDocumentDataWorksItem>>;
}
/**
 * Item in Personal Works → Works
 *
 */
export interface PersonalWorksDocumentDataWorksItem {
  /**
   * Thumbnail src field in *Personal Works → Works*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: personal_works.works[].thumbnail_src
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  thumbnail_src: prismicT.ImageField<never>;
  /**
   * Link field in *Personal Works → Works*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: personal_works.works[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismicT.LinkField;
  /**
   * Thumbnail external src field in *Personal Works → Works*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: personal_works.works[].thumbnail_external_src
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  thumbnail_external_src: prismicT.LinkField;
  /**
   * Icon field in *Personal Works → Works*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: personal_works.works[].icon
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  icon: prismicT.SelectField<"unsplash" | "youtube">;
}
/**
 * Personal Works document from Prismic
 *
 * - **API ID**: `personal_works`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PersonalWorksDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<PersonalWorksDocumentData>,
    "personal_works",
    Lang
  >;
/** Content for Profile documents */
interface ProfileDocumentData {
  /**
   * First Name field in *Profile*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.first_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  first_name: prismicT.KeyTextField;
  /**
   * Last Name field in *Profile*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.last_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  last_name: prismicT.KeyTextField;
  /**
   * Image field in *Profile*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<"x2">;
  /**
   * Email field in *Profile*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  email: prismicT.KeyTextField;
  /**
   * Social Networks field in *Profile*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.social_networks[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  social_networks: prismicT.GroupField<
    Simplify<ProfileDocumentDataSocialNetworksItem>
  >;
  /**
   * Traits field in *Profile*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.traits
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  traits: prismicT.KeyTextField;
}
/**
 * Item in Profile → Social Networks
 *
 */
export interface ProfileDocumentDataSocialNetworksItem {
  /**
   * Name field in *Profile → Social Networks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.social_networks[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField;
  /**
   * Link field in *Profile → Social Networks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.social_networks[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismicT.LinkField;
  /**
   * Icon field in *Profile → Social Networks*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.social_networks[].icon
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  icon: prismicT.SelectField<
    | "500px"
    | "codepen"
    | "dribbble"
    | "github"
    | "instagram"
    | "linkedin"
    | "spotify"
    | "twitter"
    | "unsplash"
    | "youtube"
  >;
}
/**
 * Profile document from Prismic
 *
 * - **API ID**: `profile`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProfileDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<ProfileDocumentData>,
    "profile",
    Lang
  >;
/** Content for Projects documents */
interface ProjectsDocumentData {
  /**
   * Projects field in *Projects*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.projects[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  projects: prismicT.GroupField<Simplify<ProjectsDocumentDataProjectsItem>>;
}
/**
 * Item in Projects → Projects
 *
 */
export interface ProjectsDocumentDataProjectsItem {
  /**
   * Name field in *Projects → Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.projects[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField;
  /**
   * Tagline field in *Projects → Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.projects[].tagline
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  tagline: prismicT.KeyTextField;
  /**
   * Link field in *Projects → Projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.projects[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismicT.LinkField;
  /**
   * Lede field in *Projects → Projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.projects[].lede
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  lede: prismicT.RichTextField;
  /**
   * Thumbnail Src field in *Projects → Projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.projects[].thumbnail_src
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  thumbnail_src: prismicT.ImageField<never>;
  /**
   * Highlight field in *Projects → Projects*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: projects.projects[].highlight
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  highlight: prismicT.BooleanField;
  /**
   * Achievements field in *Projects → Projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.projects[].achievements
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  achievements: prismicT.RichTextField;
  /**
   * Architecture field in *Projects → Projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.projects[].architecture
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  architecture: prismicT.RichTextField;
  /**
   * Libraries field in *Projects → Projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.projects[].libraries
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  libraries: prismicT.RichTextField;
}
/**
 * Projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<ProjectsDocumentData>,
    "projects",
    Lang
  >;
/** Content for Skills documents */
interface SkillsDocumentData {
  /**
   * Skills field in *Skills*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.skills[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  skills: prismicT.GroupField<Simplify<SkillsDocumentDataSkillsItem>>;
}
/**
 * Item in Skills → Skills
 *
 */
export interface SkillsDocumentDataSkillsItem {
  /**
   * Label field in *Skills → Skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.skills[].label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismicT.KeyTextField;
  /**
   * Filling field in *Skills → Skills*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.skills[].filling
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  filling: prismicT.NumberField;
  /**
   * Progress field in *Skills → Skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.skills[].progress
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  progress: prismicT.KeyTextField;
}
/**
 * Skills document from Prismic
 *
 * - **API ID**: `skills`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SkillsDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<Simplify<SkillsDocumentData>, "skills", Lang>;
/** Content for Tools documents */
interface ToolsDocumentData {
  /**
   * tools field in *Tools*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tools.tools
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  tools: prismicT.RichTextField;
}
/**
 * Tools document from Prismic
 *
 * - **API ID**: `tools`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ToolsDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<Simplify<ToolsDocumentData>, "tools", Lang>;
export type AllDocumentTypes =
  | AcademicQualificationsDocument
  | CareerExperiencesDocument
  | HomeDocument
  | InterestsDocument
  | LanguagesDocument
  | OpenSourceDocument
  | PersonalWorksDocument
  | ProfileDocument
  | ProjectsDocument
  | SkillsDocument
  | ToolsDocument;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      AcademicQualificationsDocumentData,
      AcademicQualificationsDocumentDataDegreesItem,
      AcademicQualificationsDocument,
      CareerExperiencesDocumentData,
      CareerExperiencesDocumentDataExperiencesItem,
      CareerExperiencesDocument,
      HomeDocumentData,
      HomeDocument,
      InterestsDocumentData,
      InterestsDocument,
      LanguagesDocumentData,
      LanguagesDocument,
      OpenSourceDocumentData,
      OpenSourceDocumentDataProjectsItem,
      OpenSourceDocument,
      PersonalWorksDocumentData,
      PersonalWorksDocumentDataWorksItem,
      PersonalWorksDocument,
      ProfileDocumentData,
      ProfileDocumentDataSocialNetworksItem,
      ProfileDocument,
      ProjectsDocumentData,
      ProjectsDocumentDataProjectsItem,
      ProjectsDocument,
      SkillsDocumentData,
      SkillsDocumentDataSkillsItem,
      SkillsDocument,
      ToolsDocumentData,
      ToolsDocument,
      AllDocumentTypes,
    };
  }
}
