// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/types";
import type * as prismicClient from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Academic Qualifications → Degrees*
 */
export interface AcademicQualificationsDocumentDataDegreesItem {
  /**
   * Establishment Name field in *Academic Qualifications → Degrees*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: academic_qualifications.degrees[].establishment_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  establishment_name: prismic.KeyTextField;

  /**
   * Establishment Link field in *Academic Qualifications → Degrees*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: academic_qualifications.degrees[].establishment_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  establishment_link: prismic.LinkField;

  /**
   * Location field in *Academic Qualifications → Degrees*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: academic_qualifications.degrees[].location
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * Graduation Year field in *Academic Qualifications → Degrees*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: academic_qualifications.degrees[].graduation_year
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  graduation_year: prismic.NumberField;

  /**
   * Title field in *Academic Qualifications → Degrees*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: academic_qualifications.degrees[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Content for Academic Qualifications documents
 */
interface AcademicQualificationsDocumentData {
  /**
   * Degrees field in *Academic Qualifications*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: academic_qualifications.degrees[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  degrees: prismic.GroupField<
    Simplify<AcademicQualificationsDocumentDataDegreesItem>
  >;
}

/**
 * Academic Qualifications document from Prismic
 *
 * - **API ID**: `academic_qualifications`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AcademicQualificationsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AcademicQualificationsDocumentData>,
    "academic_qualifications",
    Lang
  >;

/**
 * Item in *Career Experiences → Experiences*
 */
export interface CareerExperiencesDocumentDataExperiencesItem {
  /**
   * Company Link field in *Career Experiences → Experiences*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: career_experiences.experiences[].company_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  company_link: prismic.LinkField;

  /**
   * Company Name field in *Career Experiences → Experiences*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: career_experiences.experiences[].company_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name: prismic.KeyTextField;

  /**
   * Location field in *Career Experiences → Experiences*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: career_experiences.experiences[].location
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * Job Title field in *Career Experiences → Experiences*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: career_experiences.experiences[].job_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_title: prismic.KeyTextField;

  /**
   * Start Date field in *Career Experiences → Experiences*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: career_experiences.experiences[].start_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  start_date: prismic.DateField;

  /**
   * Present field in *Career Experiences → Experiences*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: career_experiences.experiences[].present
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  present: prismic.BooleanField;

  /**
   * End Date field in *Career Experiences → Experiences*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: career_experiences.experiences[].end_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  end_date: prismic.DateField;

  /**
   * Contract Type field in *Career Experiences → Experiences*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: career_experiences.experiences[].contract_type
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contract_type: prismic.KeyTextField;

  /**
   * Lede field in *Career Experiences → Experiences*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: career_experiences.experiences[].lede
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  lede: prismic.RichTextField;

  /**
   * Projects field in *Career Experiences → Experiences*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: career_experiences.experiences[].projects
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  projects: prismic.ContentRelationshipField<"projects">;
}

/**
 * Content for Career Experiences documents
 */
interface CareerExperiencesDocumentData {
  /**
   * Experiences field in *Career Experiences*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: career_experiences.experiences[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  experiences: prismic.GroupField<
    Simplify<CareerExperiencesDocumentDataExperiencesItem>
  >;
}

/**
 * Career Experiences document from Prismic
 *
 * - **API ID**: `career_experiences`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CareerExperiencesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CareerExperiencesDocumentData>,
    "career_experiences",
    Lang
  >;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Title 1 field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_1: prismic.KeyTextField;

  /**
   * Paragraph 1 field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.paragraph_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph_1: prismic.RichTextField;

  /**
   * Title 2 field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_2: prismic.KeyTextField;

  /**
   * Paragraph 2 field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.paragraph_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph_2: prismic.RichTextField;

  /**
   * Skills Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.skills_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  skills_section_title: prismic.KeyTextField;

  /**
   * Tools Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.tools_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tools_section_title: prismic.KeyTextField;

  /**
   * Profile Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.profile_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  profile_section_title: prismic.KeyTextField;

  /**
   * Academic Qualifications Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.academic_qualifications_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  academic_qualifications_section_title: prismic.KeyTextField;

  /**
   * Languages Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.languages_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  languages_section_title: prismic.KeyTextField;

  /**
   * Interests Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.interests_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  interests_section_title: prismic.KeyTextField;

  /**
   * Social Media Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.social_media_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  social_media_section_title: prismic.KeyTextField;

  /**
   * Career Experiences Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.career_experiences_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  career_experiences_section_title: prismic.KeyTextField;

  /**
   * Open Source Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.open_source_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  open_source_section_title: prismic.KeyTextField;

  /**
   * Personal Works Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.personal_works_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  personal_works_section_title: prismic.KeyTextField;

  /**
   * Get In Touch Section Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.get_in_touch_section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  get_in_touch_section_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Content for Interests documents
 */
interface InterestsDocumentData {
  /**
   * Interests field in *Interests*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: interests.interests
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  interests: prismic.RichTextField;
}

/**
 * Interests document from Prismic
 *
 * - **API ID**: `interests`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InterestsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<InterestsDocumentData>,
    "interests",
    Lang
  >;

/**
 * Content for Languages documents
 */
interface LanguagesDocumentData {
  /**
   * Languages field in *Languages*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: languages.languages
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  languages: prismic.RichTextField;
}

/**
 * Languages document from Prismic
 *
 * - **API ID**: `languages`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LanguagesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LanguagesDocumentData>,
    "languages",
    Lang
  >;

/**
 * Item in *Open-Source → Projects*
 */
export interface OpenSourceDocumentDataProjectsItem {
  /**
   * Name field in *Open-Source → Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: open_source.projects[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Link field in *Open-Source → Projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: open_source.projects[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Lede field in *Open-Source → Projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: open_source.projects[].lede
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  lede: prismic.RichTextField;

  /**
   * Description field in *Open-Source → Projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: open_source.projects[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Content for Open-Source documents
 */
interface OpenSourceDocumentData {
  /**
   * Projects field in *Open-Source*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: open_source.projects[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  projects: prismic.GroupField<Simplify<OpenSourceDocumentDataProjectsItem>>;
}

/**
 * Open-Source document from Prismic
 *
 * - **API ID**: `open_source`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OpenSourceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OpenSourceDocumentData>,
    "open_source",
    Lang
  >;

/**
 * Item in *Personal Works → Works*
 */
export interface PersonalWorksDocumentDataWorksItem {
  /**
   * Thumbnail src field in *Personal Works → Works*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: personal_works.works[].thumbnail_src
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail_src: prismic.ImageField<never>;

  /**
   * Link field in *Personal Works → Works*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: personal_works.works[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Thumbnail external src field in *Personal Works → Works*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: personal_works.works[].thumbnail_external_src
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  thumbnail_external_src: prismic.LinkField;

  /**
   * Icon field in *Personal Works → Works*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: personal_works.works[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<"unsplash" | "youtube">;
}

/**
 * Content for Personal Works documents
 */
interface PersonalWorksDocumentData {
  /**
   * Paragraph field in *Personal Works*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: personal_works.paragraph
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * Works field in *Personal Works*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: personal_works.works[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  works: prismic.GroupField<Simplify<PersonalWorksDocumentDataWorksItem>>;
}

/**
 * Personal Works document from Prismic
 *
 * - **API ID**: `personal_works`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PersonalWorksDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PersonalWorksDocumentData>,
    "personal_works",
    Lang
  >;

/**
 * Item in *Profile → Social Networks*
 */
export interface ProfileDocumentDataSocialNetworksItem {
  /**
   * Name field in *Profile → Social Networks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.social_networks[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Link field in *Profile → Social Networks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.social_networks[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Icon field in *Profile → Social Networks*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.social_networks[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<
    | "500px"
    | "codepen"
    | "dribbble"
    | "github"
    | "instagram"
    | "linkedin"
    | "spotify"
    | "xcom"
    | "unsplash"
    | "youtube"
  >;
}

/**
 * Content for Profile documents
 */
interface ProfileDocumentData {
  /**
   * First Name field in *Profile*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.first_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  first_name: prismic.KeyTextField;

  /**
   * Last Name field in *Profile*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.last_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  last_name: prismic.KeyTextField;

  /**
   * Image field in *Profile*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"x2">;

  /**
   * Email field in *Profile*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Social Networks field in *Profile*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.social_networks[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_networks: prismic.GroupField<
    Simplify<ProfileDocumentDataSocialNetworksItem>
  >;

  /**
   * Traits field in *Profile*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.traits
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  traits: prismic.KeyTextField;
}

/**
 * Profile document from Prismic
 *
 * - **API ID**: `profile`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProfileDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProfileDocumentData>,
    "profile",
    Lang
  >;

/**
 * Item in *Projects → Projects*
 */
export interface ProjectsDocumentDataProjectsItem {
  /**
   * Name field in *Projects → Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.projects[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Tagline field in *Projects → Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.projects[].tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Link field in *Projects → Projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.projects[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Lede field in *Projects → Projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.projects[].lede
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  lede: prismic.RichTextField;

  /**
   * Thumbnail Src field in *Projects → Projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.projects[].thumbnail_src
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail_src: prismic.ImageField<never>;

  /**
   * Highlight field in *Projects → Projects*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: projects.projects[].highlight
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  highlight: prismic.BooleanField;

  /**
   * Achievements field in *Projects → Projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.projects[].achievements
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  achievements: prismic.RichTextField;

  /**
   * Architecture field in *Projects → Projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.projects[].architecture
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  architecture: prismic.RichTextField;
}

/**
 * Content for Projects documents
 */
interface ProjectsDocumentData {
  /**
   * Projects field in *Projects*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.projects[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  projects: prismic.GroupField<Simplify<ProjectsDocumentDataProjectsItem>>;
}

/**
 * Projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectsDocumentData>,
    "projects",
    Lang
  >;

/**
 * Item in *Skills → Skills*
 */
export interface SkillsDocumentDataSkillsItem {
  /**
   * Label field in *Skills → Skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.skills[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Filling field in *Skills → Skills*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.skills[].filling
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  filling: prismic.NumberField;

  /**
   * Progress field in *Skills → Skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.skills[].progress
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  progress: prismic.KeyTextField;
}

/**
 * Content for Skills documents
 */
interface SkillsDocumentData {
  /**
   * Skills field in *Skills*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.skills[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  skills: prismic.GroupField<Simplify<SkillsDocumentDataSkillsItem>>;
}

/**
 * Skills document from Prismic
 *
 * - **API ID**: `skills`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SkillsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SkillsDocumentData>, "skills", Lang>;

/**
 * Content for Tools documents
 */
interface ToolsDocumentData {
  /**
   * tools field in *Tools*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tools.tools
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tools: prismic.RichTextField;
}

/**
 * Tools document from Prismic
 *
 * - **API ID**: `tools`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ToolsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ToolsDocumentData>, "tools", Lang>;

export type AllDocumentTypes =
  | AcademicQualificationsDocument
  | CareerExperiencesDocument
  | HomeDocument
  | InterestsDocument
  | LanguagesDocument
  | OpenSourceDocument
  | PersonalWorksDocument
  | ProfileDocument
  | ProjectsDocument
  | SkillsDocument
  | ToolsDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismicClient.ClientConfig
    ): prismicClient.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AcademicQualificationsDocument,
      AcademicQualificationsDocumentData,
      AcademicQualificationsDocumentDataDegreesItem,
      CareerExperiencesDocument,
      CareerExperiencesDocumentData,
      CareerExperiencesDocumentDataExperiencesItem,
      HomeDocument,
      HomeDocumentData,
      InterestsDocument,
      InterestsDocumentData,
      LanguagesDocument,
      LanguagesDocumentData,
      OpenSourceDocument,
      OpenSourceDocumentData,
      OpenSourceDocumentDataProjectsItem,
      PersonalWorksDocument,
      PersonalWorksDocumentData,
      PersonalWorksDocumentDataWorksItem,
      ProfileDocument,
      ProfileDocumentData,
      ProfileDocumentDataSocialNetworksItem,
      ProjectsDocument,
      ProjectsDocumentData,
      ProjectsDocumentDataProjectsItem,
      SkillsDocument,
      SkillsDocumentData,
      SkillsDocumentDataSkillsItem,
      ToolsDocument,
      ToolsDocumentData,
      AllDocumentTypes,
    };
  }
}
